spring.datasource.url=jdbc:postgresql://dpg-d71ob67gi27c73fk8hig-a.oregon-postgres.render.com:5432/ticketbooking_zyih
spring.datasource.username=ticketbooking
spring.datasource.password=55QwwDETAh6wOw9HoboJikT0cmDP5mFB
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
server.servlet.session.timeout=60m